import React, { useState } from 'react';
import {
  FileText,
  Lightbulb,
  Clock,
  Copy,
  Check,
  Code,
  ShieldCheck,
  AlertTriangle,
  Zap
} from 'lucide-react';
import { VideoNoteAnalysis } from '../types/notes';

interface SummaryTabProps {
  analysis: VideoNoteAnalysis;
}

export const SummaryTab: React.FC<SummaryTabProps> = ({ analysis }) => {
  const [copiedSection, setCopiedSection] = useState<string | null>(null);

  const copyText = (text: string, sectionId: string) => {
    navigator.clipboard.writeText(text);
    setCopiedSection(sectionId);
    setTimeout(() => setCopiedSection(null), 2000);
  };

  const fullMarkdownSummary = `
# ${analysis.videoTitle}
Video Link: ${analysis.videoUrl}

## Overall Executive Summary
${analysis.overallSummary}

${analysis.mentalModels ? `## Mental Models & Core Frameworks\n${analysis.mentalModels.map(m => `- ${m}`).join('\n')}\n` : ''}
${analysis.proTipsGlobal ? `## Golden Rules & Pro Tips\n${analysis.proTipsGlobal.map(t => `- ${t}`).join('\n')}\n` : ''}
${analysis.trapsToAvoidGlobal ? `## Traps to Avoid\n${analysis.trapsToAvoidGlobal.map(tr => `- ${tr}`).join('\n')}\n` : ''}

## Key Takeaways
${analysis.keyTakeaways.map((kt) => `- **${kt.title}**: ${kt.description}`).join('\n')}

## Chapter Outline
${analysis.outline
  .map(
    (ch) => `### ${ch.timestamp} - ${ch.title}\n${ch.summary}\n${ch.keyPoints.map((p) => `  - ${p}`).join('\n')}`
  )
  .join('\n\n')}
`;

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 24 }}>
      {/* Top Overall Summary Header Card */}
      <div className="glass-card" style={{ padding: 28, border: '1px solid var(--border-active)' }}>
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', borderBottom: '1px solid rgba(255,255,255,0.08)', paddingBottom: 16, marginBottom: 16 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
            <div style={{ width: 40, height: 40, borderRadius: 12, background: 'rgba(99, 102, 241, 0.12)', border: '1px solid rgba(99, 102, 241, 0.3)', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#818cf8' }}>
              <FileText style={{ width: 20, height: 20 }} />
            </div>
            <div>
              <h3 style={{ fontSize: 18, fontWeight: 800, color: '#fff' }}>Executive Video Synthesis</h3>
              <p style={{ fontSize: 12, color: 'var(--text-muted)' }}>High-density academic synthesis generated by Gemini</p>
            </div>
          </div>

          <button
            onClick={() => copyText(fullMarkdownSummary, 'full')}
            className="btn-secondary"
            style={{ fontSize: 12, padding: '8px 14px' }}
          >
            {copiedSection === 'full' ? (
              <>
                <Check style={{ width: 14, height: 14, color: '#34d399' }} />
                <span>Copied Master Notes</span>
              </>
            ) : (
              <>
                <Copy style={{ width: 14, height: 14, color: '#94a3b8' }} />
                <span>Copy Full Markdown</span>
              </>
            )}
          </button>
        </div>

        <p style={{ fontSize: 15, color: '#e2e8f0', lineHeight: 1.7, marginBottom: 16 }}>
          {analysis.overallSummary}
        </p>

        {/* Mental Models Grid */}
        {analysis.mentalModels && analysis.mentalModels.length > 0 && (
          <div style={{ paddingTop: 16, borderTop: '1px solid rgba(255,255,255,0.06)', display: 'flex', flexDirection: 'column', gap: 10 }}>
            <div style={{ fontSize: 12, fontWeight: 800, textTransform: 'uppercase', color: '#818cf8', display: 'flex', alignItems: 'center', gap: 6 }}>
              <Zap style={{ width: 14, height: 14 }} />
              <span>Core Mental Models & Paradigms</span>
            </div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
              {analysis.mentalModels.map((model, mIdx) => (
                <div key={mIdx} style={{ padding: 10, borderRadius: 8, background: 'rgba(99, 102, 241, 0.1)', border: '1px solid rgba(99, 102, 241, 0.2)', fontSize: 13, color: '#c7d2fe', display: 'flex', alignItems: 'flex-start', gap: 8 }}>
                  <span style={{ fontWeight: 800, color: '#818cf8' }}>0{mIdx + 1}.</span>
                  <span>{model}</span>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>

      {/* Traps to Avoid & Golden Rules Row */}
      {(analysis.trapsToAvoidGlobal || analysis.proTipsGlobal) && (
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))', gap: 16 }}>
          {analysis.trapsToAvoidGlobal && analysis.trapsToAvoidGlobal.length > 0 && (
            <div className="glass-card" style={{ padding: 20, border: '1px solid rgba(244, 63, 94, 0.3)', background: 'rgba(136, 19, 55, 0.2)' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 8, fontSize: 13, fontWeight: 800, color: '#f43f5e', marginBottom: 10 }}>
                <AlertTriangle style={{ width: 16, height: 16 }} />
                <span>Critical Traps & Pitfalls to Avoid</span>
              </div>
              <ul style={{ listStyle: 'none', display: 'flex', flexDirection: 'column', gap: 6 }}>
                {analysis.trapsToAvoidGlobal.map((trap, tIdx) => (
                  <li key={tIdx} style={{ fontSize: 12, color: '#fecdd3', display: 'flex', alignItems: 'flex-start', gap: 8 }}>
                    <span style={{ color: '#f43f5e', fontWeight: 800 }}>•</span>
                    <span>{trap}</span>
                  </li>
                ))}
              </ul>
            </div>
          )}

          {analysis.proTipsGlobal && analysis.proTipsGlobal.length > 0 && (
            <div className="glass-card" style={{ padding: 20, border: '1px solid rgba(16, 185, 129, 0.3)', background: 'rgba(6, 78, 59, 0.2)' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 8, fontSize: 13, fontWeight: 800, color: '#34d399', marginBottom: 10 }}>
                <ShieldCheck style={{ width: 16, height: 16 }} />
                <span>Golden Rules for Mastery</span>
              </div>
              <ul style={{ listStyle: 'none', display: 'flex', flexDirection: 'column', gap: 6 }}>
                {analysis.proTipsGlobal.map((tip, tpIdx) => (
                  <li key={tpIdx} style={{ fontSize: 12, color: '#a7f3d0', display: 'flex', alignItems: 'flex-start', gap: 8 }}>
                    <span style={{ color: '#34d399', fontWeight: 800 }}>✓</span>
                    <span>{tip}</span>
                  </li>
                ))}
              </ul>
            </div>
          )}
        </div>
      )}

      {/* Key Takeaways Grid */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
          <Lightbulb style={{ width: 20, height: 20, color: '#fbbf24' }} />
          <h3 style={{ fontSize: 20, fontWeight: 800, color: '#fff' }}>Key Takeaways & Principles</h3>
        </div>

        <div className="takeaways-grid">
          {analysis.keyTakeaways.map((takeaway, idx) => (
            <div key={takeaway.id || idx} className="glass-card-interactive takeaway-card">
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                <span style={{ fontSize: 11, fontWeight: 700, textTransform: 'uppercase', padding: '3px 10px', borderRadius: 20, background: 'rgba(99, 102, 241, 0.12)', color: '#a5b4fc', border: '1px solid rgba(99, 102, 241, 0.25)' }}>
                  {takeaway.tag || `Insight #${idx + 1}`}
                </span>
                <button
                  onClick={() => copyText(`${takeaway.title}: ${takeaway.description}`, takeaway.id)}
                  style={{ color: '#64748b', padding: 4 }}
                  title="Copy snippet"
                >
                  {copiedSection === takeaway.id ? (
                    <Check style={{ width: 14, height: 14, color: '#34d399' }} />
                  ) : (
                    <Copy style={{ width: 14, height: 14 }} />
                  )}
                </button>
              </div>

              <h4 style={{ fontSize: 16, fontWeight: 800, color: '#fff' }}>
                {takeaway.title}
              </h4>

              <p style={{ fontSize: 13, color: '#cbd5e1', lineHeight: 1.6 }}>
                {takeaway.description}
              </p>
            </div>
          ))}
        </div>
      </div>

      {/* Timestamped Outline Section */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 16, paddingTop: 16 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
          <Clock style={{ width: 20, height: 20, color: '#818cf8' }} />
          <h3 style={{ fontSize: 20, fontWeight: 800, color: '#fff' }}>Structured Chapter Outline & Code</h3>
        </div>

        <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
          {analysis.outline.map((chapter, idx) => (
            <div key={chapter.id || idx} className="glass-card chapter-card">
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                <span style={{ fontSize: 12, fontFamily: 'monospace', fontWeight: 700, padding: '4px 12px', borderRadius: 8, background: 'rgba(99, 102, 241, 0.15)', color: '#a5b4fc', border: '1px solid rgba(99, 102, 241, 0.3)' }}>
                  {chapter.timestamp}
                </span>
                <span style={{ fontSize: 12, color: '#94a3b8' }}>Chapter {idx + 1}</span>
              </div>

              <h4 style={{ fontSize: 16, fontWeight: 800, color: '#fff' }}>
                {chapter.title}
              </h4>

              <p style={{ fontSize: 13, color: '#cbd5e1', lineHeight: 1.6 }}>
                {chapter.summary}
              </p>

              {chapter.keyPoints && chapter.keyPoints.length > 0 && (
                <div style={{ paddingTop: 12, borderTop: '1px solid rgba(255,255,255,0.06)', display: 'flex', flexDirection: 'column', gap: 6 }}>
                  <span style={{ fontSize: 11, fontWeight: 700, color: '#94a3b8', textTransform: 'uppercase' }}>
                    Key Concepts Covered:
                  </span>
                  <ul style={{ listStyle: 'none', display: 'flex', flexDirection: 'column', gap: 4 }}>
                    {chapter.keyPoints.map((point, pIdx) => (
                      <li key={pIdx} style={{ fontSize: 12, color: '#e2e8f0', display: 'flex', alignItems: 'flex-start', gap: 8 }}>
                        <span style={{ width: 6, height: 6, borderRadius: '50%', background: '#818cf8', marginTop: 6, flexShrink: 0 }} />
                        <span>{point}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              {/* Code Snippets */}
              {chapter.codeSnippets && chapter.codeSnippets.length > 0 && (
                <div style={{ marginTop: 8 }}>
                  {chapter.codeSnippets.map((snip, snipIdx) => (
                    <div key={snipIdx} style={{ background: '#090d16', padding: 12, borderRadius: 8, border: '1px solid #1e293b' }}>
                      <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 11, color: '#818cf8', fontWeight: 700, marginBottom: 4 }}>
                        <span style={{ display: 'flex', alignItems: 'center', gap: 4 }}>
                          <Code style={{ width: 12, height: 12 }} />
                          <span>Code / Prompt Reference</span>
                        </span>
                        <span style={{ textTransform: 'uppercase' }}>{snip.language || 'code'}</span>
                      </div>
                      <pre style={{ margin: 0, fontFamily: 'Consolas, monospace', fontSize: 12, color: '#38bdf8', whiteSpace: 'pre-wrap' }}>
                        {snip.code}
                      </pre>
                      {snip.explanation && (
                        <div style={{ fontSize: 11, color: '#94a3b8', marginTop: 4, fontStyle: 'italic' }}>
                          {snip.explanation}
                        </div>
                      )}
                    </div>
                  ))}
                </div>
              )}
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};
